services:
  hac-pharma-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hac-pharma-frontend
    ports:
      - "4000:4000"
    restart: always
    environment:
      - PORT=4000
